using Microsoft.CodeAnalysis;

namespace Facette.Generator;

[Generator]
public sealed class FacetteGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Facette.Abstractions.FacetteAttribute",
            predicate: static (node, _) => true,
            transform: static (ctx, _) => ctx
        );

        context.RegisterSourceOutput(targets, static (spc, ctx) =>
        {
            var symbol = ctx.TargetSymbol as INamedTypeSymbol;
            if (symbol is null) return;

            var name = symbol.Name;
            var ns = symbol.ContainingNamespace.ToDisplayString();

            var code =
                "// <auto-generated />\n" +
                "#nullable enable\n" +
                "\n" +
                "namespace " + ns + ";\n" +
                "\n" +
                "public partial record " + name + "\n" +
                "{\n" +
                "}\n";

            spc.AddSource(name + ".g.cs", code);
        });
    }
}
