using Facette.Generator.Builders;
using Facette.Generator.Models;
using Microsoft.CodeAnalysis;

namespace Facette.Generator
{
    [Generator]
    public sealed class FacetteGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
                "Facette.Abstractions.FacetteAttribute",
                predicate: static (node, _) => true,
                transform: static (ctx, _) => ModelBuilder.Build(ctx)
            );

            context.RegisterSourceOutput(targets, static (spc, model) =>
            {
                if (model == null)
                {
                    return;
                }

                // Report any diagnostics collected during model building
                bool hasErrors = false;
                foreach (var diag in model.Diagnostics)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        diag.Descriptor,
                        diag.ToLocation(),
                        diag.MessageArgs));

                    if (diag.Descriptor.DefaultSeverity == DiagnosticSeverity.Error)
                    {
                        hasErrors = true;
                    }
                }

                // Don't generate code if there are errors
                if (hasErrors)
                {
                    return;
                }

                EmitDtoSource(spc, model);

                if (model.GenerateMapper)
                {
                    var mapperCode = MapperClassBuilder.Build(model);
                    spc.AddSource(model.TypeName + "Mapper.g.cs", mapperCode);
                }
            });
        }

        private static void EmitDtoSource(SourceProductionContext spc, FacetteTargetModel model)
        {
            var properties = PropertyBuilder.Build(model.Properties);

            var fromSource = MappingBuilder.BuildFromSource(
                model.TypeName,
                model.SourceTypeFullName,
                model.Properties);

            var mappingMethods = "\n\n" + fromSource;

            if (model.GenerateToSource)
            {
                var toSource = MappingBuilder.BuildToSource(
                    model.SourceTypeFullName,
                    model.Properties);
                mappingMethods = mappingMethods + "\n\n" + toSource;
            }

            if (model.GenerateProjection)
            {
                var projection = ProjectionBuilder.Build(
                    model.TypeName,
                    model.SourceTypeFullName,
                    model.Properties);
                mappingMethods = mappingMethods + "\n\n" + projection;
            }

            var nsLine = string.IsNullOrEmpty(model.Namespace) ? "" : "namespace " + model.Namespace + ";\n\n";

            var code = "// <auto-generated />\n"
                + "#nullable enable\n\n"
                + nsLine
                + "public partial record " + model.TypeName + "\n"
                + "{\n"
                + properties
                + mappingMethods + "\n"
                + "}\n";

            spc.AddSource(model.TypeName + ".g.cs", code);
        }
    }
}
