using Facette.Generator.Models;

namespace Facette.Generator.Builders
{
    public static class MapperClassBuilder
    {
        public static string Build(FacetteTargetModel model)
        {
            var sb = new IndentedStringBuilder();

            sb.Append(FacetteGenerator.AutoGeneratedHeader);
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.AppendLine("namespace " + model.Namespace + ";");
                sb.AppendLine();
            }

            sb.AppendLine("public static partial class " + model.TypeName + "Mapper");
            sb.AppendLine("{");
            sb.Indent();

            // ToDto extension method (always generated)
            var addParams = "";
            var addArgs = "";
            foreach (var addSrc in model.AdditionalSources)
            {
                addParams += ", " + addSrc.SourceTypeFullName + " " + addSrc.ParameterName;
                addArgs += ", " + addSrc.ParameterName;
            }
            sb.AppendLine("public static " + model.TypeName + " ToDto(this " + model.SourceTypeFullName + " source" + addParams + ")");
            sb.AppendLine("    => " + model.TypeName + ".FromSource(source" + addArgs + ");");

            // ToSource extension method (conditional)
            if (model.GenerateToSource)
            {
                sb.AppendLine();
                sb.AppendLine("public static " + model.SourceTypeFullName + " ToSource(this " + model.TypeName + " dto)");
                sb.AppendLine("    => dto.ToSource();");
            }

            // ProjectToDto extension method (conditional)
            if (model.GenerateProjection)
            {
                sb.AppendLine();
                sb.AppendLine("public static System.Linq.IQueryable<" + model.TypeName + "> ProjectToDto(this System.Linq.IQueryable<" + model.SourceTypeFullName + "> query)");
                sb.AppendLine("    => query.Select(" + model.TypeName + ".Projection);");

                sb.AppendLine();
                sb.AppendLine("public static System.Linq.IQueryable<" + model.SourceTypeFullName + "> WhereDto(this System.Linq.IQueryable<" + model.SourceTypeFullName + "> query, System.Linq.Expressions.Expression<System.Func<" + model.TypeName + ", bool>> predicate)");
                sb.AppendLine("    => query.Where(" + model.TypeName + ".MapExpression(predicate));");
            }

            // Collection ToDto extensions (always generated)
            var hasAdditionalSources = model.AdditionalSources.Length > 0;
            sb.AppendLine();
            sb.AppendLine("public static IEnumerable<" + model.TypeName + "> ToDto(this IEnumerable<" + model.SourceTypeFullName + "> sources" + addParams + ")");
            if (hasAdditionalSources)
                sb.AppendLine("    => sources.Select(source => " + model.TypeName + ".FromSource(source" + addArgs + "));");
            else
                sb.AppendLine("    => sources.Select(" + model.TypeName + ".FromSource);");

            sb.AppendLine();
            sb.AppendLine("public static List<" + model.TypeName + "> ToDtoList(this IEnumerable<" + model.SourceTypeFullName + "> sources" + addParams + ")");
            if (hasAdditionalSources)
                sb.AppendLine("    => sources.Select(source => " + model.TypeName + ".FromSource(source" + addArgs + ")).ToList();");
            else
                sb.AppendLine("    => sources.Select(" + model.TypeName + ".FromSource).ToList();");

            // Collection ToSource extensions (conditional)
            if (model.GenerateToSource)
            {
                sb.AppendLine();
                sb.AppendLine("public static IEnumerable<" + model.SourceTypeFullName + "> ToSource(this IEnumerable<" + model.TypeName + "> dtos)");
                sb.AppendLine("    => dtos.Select(dto => dto.ToSource());");

                sb.AppendLine();
                sb.AppendLine("public static List<" + model.SourceTypeFullName + "> ToSourceList(this IEnumerable<" + model.TypeName + "> dtos)");
                sb.AppendLine("    => dtos.Select(dto => dto.ToSource()).ToList();");
            }

            // IAsyncEnumerable extensions (NET 8.0+)
            sb.AppendLine();
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("public static async IAsyncEnumerable<" + model.TypeName + "> ToDtoAsync(this IAsyncEnumerable<" + model.SourceTypeFullName + "> sources" + addParams + ")");
            sb.AppendLine("{");
            sb.Indent();
            sb.AppendLine("await foreach (var source in sources)");
            sb.AppendLine("{");
            sb.Indent();
            sb.AppendLine("yield return " + model.TypeName + ".FromSource(source" + addArgs + ");");
            sb.Unindent();
            sb.AppendLine("}");
            sb.Unindent();
            sb.AppendLine("}");

            if (model.GenerateToSource)
            {
                sb.AppendLine();
                sb.AppendLine("public static async IAsyncEnumerable<" + model.SourceTypeFullName + "> ToSourceAsync(this IAsyncEnumerable<" + model.TypeName + "> dtos)");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine("await foreach (var dto in dtos)");
                sb.AppendLine("{");
                sb.Indent();
                sb.AppendLine("yield return dto.ToSource();");
                sb.Unindent();
                sb.AppendLine("}");
                sb.Unindent();
                sb.AppendLine("}");
            }

            sb.AppendLine("#endif");

            sb.Unindent();
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
