using System.Text;
using Facette.Generator.Models;

namespace Facette.Generator.Builders
{
    public static class MapperClassBuilder
    {
        public static string Build(FacetteTargetModel model)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.AppendLine("namespace " + model.Namespace + ";");
                sb.AppendLine();
            }

            sb.AppendLine("public static partial class " + model.TypeName + "Mapper");
            sb.AppendLine("{");

            // ToDto extension method (always generated)
            var addParams = "";
            var addArgs = "";
            foreach (var addSrc in model.AdditionalSources)
            {
                addParams += ", " + addSrc.SourceTypeFullName + " " + addSrc.ParameterName;
                addArgs += ", " + addSrc.ParameterName;
            }
            sb.AppendLine("    public static " + model.TypeName + " ToDto(this " + model.SourceTypeFullName + " source" + addParams + ")");
            sb.AppendLine("        => " + model.TypeName + ".FromSource(source" + addArgs + ");");

            // ToSource extension method (conditional)
            if (model.GenerateToSource)
            {
                sb.AppendLine();
                sb.AppendLine("    public static " + model.SourceTypeFullName + " ToSource(this " + model.TypeName + " dto)");
                sb.AppendLine("        => dto.ToSource();");
            }

            // ProjectToDto extension method (conditional)
            if (model.GenerateProjection)
            {
                sb.AppendLine();
                sb.AppendLine("    public static System.Linq.IQueryable<" + model.TypeName + "> ProjectToDto(this System.Linq.IQueryable<" + model.SourceTypeFullName + "> query)");
                sb.AppendLine("        => query.Select(" + model.TypeName + ".Projection);");

                sb.AppendLine();
                sb.AppendLine("    public static System.Linq.IQueryable<" + model.SourceTypeFullName + "> WhereDto(this System.Linq.IQueryable<" + model.SourceTypeFullName + "> query, System.Linq.Expressions.Expression<System.Func<" + model.TypeName + ", bool>> predicate)");
                sb.AppendLine("        => query.Where(" + model.TypeName + ".MapExpression(predicate));");
            }

            // Collection ToDto extensions (always generated)
            var hasAdditionalSources = model.AdditionalSources.Length > 0;
            sb.AppendLine();
            sb.AppendLine("    public static IEnumerable<" + model.TypeName + "> ToDto(this IEnumerable<" + model.SourceTypeFullName + "> sources" + addParams + ")");
            if (hasAdditionalSources)
                sb.AppendLine("        => sources.Select(source => " + model.TypeName + ".FromSource(source" + addArgs + "));");
            else
                sb.AppendLine("        => sources.Select(" + model.TypeName + ".FromSource);");

            sb.AppendLine();
            sb.AppendLine("    public static List<" + model.TypeName + "> ToDtoList(this IEnumerable<" + model.SourceTypeFullName + "> sources" + addParams + ")");
            if (hasAdditionalSources)
                sb.AppendLine("        => sources.Select(source => " + model.TypeName + ".FromSource(source" + addArgs + ")).ToList();");
            else
                sb.AppendLine("        => sources.Select(" + model.TypeName + ".FromSource).ToList();");

            // Collection ToSource extensions (conditional)
            if (model.GenerateToSource)
            {
                sb.AppendLine();
                sb.AppendLine("    public static IEnumerable<" + model.SourceTypeFullName + "> ToSource(this IEnumerable<" + model.TypeName + "> dtos)");
                sb.AppendLine("        => dtos.Select(dto => dto.ToSource());");

                sb.AppendLine();
                sb.AppendLine("    public static List<" + model.SourceTypeFullName + "> ToSourceList(this IEnumerable<" + model.TypeName + "> dtos)");
                sb.AppendLine("        => dtos.Select(dto => dto.ToSource()).ToList();");
            }

            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
