using System.Text;
using Facette.Generator.Models;

namespace Facette.Generator.Builders
{
    public static class MapperClassBuilder
    {
        public static string Build(FacetteTargetModel model)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.AppendLine("namespace " + model.Namespace + ";");
                sb.AppendLine();
            }

            sb.AppendLine("public static partial class " + model.TypeName + "Mapper");
            sb.AppendLine("{");

            // ToDto extension method (always generated)
            sb.AppendLine("    public static " + model.TypeName + " ToDto(this " + model.SourceTypeFullName + " source)");
            sb.AppendLine("        => " + model.TypeName + ".FromSource(source);");

            // ToSource extension method (conditional)
            if (model.GenerateToSource)
            {
                sb.AppendLine();
                sb.AppendLine("    public static " + model.SourceTypeFullName + " ToSource(this " + model.TypeName + " dto)");
                sb.AppendLine("        => dto.ToSource();");
            }

            // ProjectToDto extension method (conditional)
            if (model.GenerateProjection)
            {
                sb.AppendLine();
                sb.AppendLine("    public static System.Linq.IQueryable<" + model.TypeName + "> ProjectToDto(this System.Linq.IQueryable<" + model.SourceTypeFullName + "> query)");
                sb.AppendLine("        => query.Select(" + model.TypeName + ".Projection);");
            }

            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
